# Generated by Django 3.1.6 on 2021-02-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OptLoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldBorder',
            new_name='SwedenCities',
        ),
    ]
